insert into users (first_name, last_name, mail, password) values ('Franco', 'Spinelli', 'franco_spinelli@hotmail.com', '1234');
insert into users (first_name, last_name, mail, password) values ('Joly', 'Brockhouse', 'jbrockhouse1@meetup.com', 'vLajSLiUd');
insert into users (first_name, last_name, mail, password) values ('Jada', 'Crutchfield', 'jcrutchfield2@webnode.com', 'gNoY7lF');
insert into users (first_name, last_name, mail, password) values ('Mervin', 'Lammertz', 'mlammertz3@tmall.com', 'bX17rlfso');
insert into users (first_name, last_name, mail, password) values ('Adah', 'Humbey', 'ahumbey4@dion.ne.jp', 'zrWxLSEx');
insert into users (first_name, last_name, mail, password) values ('Whitaker', 'Junkison', 'wjunkison5@reverbnation.com', 'O536T8');
insert into users (first_name, last_name, mail, password) values ('Baird', 'Rosenbarg', 'brosenbarg6@freewebs.com', 'P0KaZnMy');
insert into users (first_name, last_name, mail, password) values ('Shara', 'Rillstone', 'srillstone7@123-reg.co.uk', 'fGnFS5ZKo');
insert into users (first_name, last_name, mail, password) values ('Merwyn', 'Poytres', 'mpoytres8@imageshack.us', 'Zx2WpS4Lr');
insert into users (first_name, last_name, mail, password) values ('Waneta', 'Body', 'wbody9@washingtonpost.com', '1yH6Qxod');
insert into users (first_name, last_name, mail, password) values ('Noemi', 'McKerlie', 'nmckerliea@toplist.cz', 'yjcQX9HeL');
insert into users (first_name, last_name, mail, password) values ('Debi', 'Fishleigh', 'dfishleighb@pinterest.com', 'bq4YxXA');
insert into users (first_name, last_name, mail, password) values ('Gilberto', 'Godleman', 'ggodlemanc@topsy.com', 'rhnKKrIuRxI');
insert into users (first_name, last_name, mail, password) values ('Eveline', 'Sebire', 'esebired@meetup.com', 'MbAnZK');
insert into users (first_name, last_name, mail, password) values ('Minor', 'Annatt', 'mannatte@irs.gov', '4R3ekhn');
insert into users (first_name, last_name, mail, password) values ('Debi', 'Dowman', 'ddowmanf@europa.eu', 'jCsqu6');
insert into users (first_name, last_name, mail, password) values ('Alexandrina', 'Studde', 'astuddeg@unicef.org', 'gLXZNe');
insert into users (first_name, last_name, mail, password) values ('Mylo', 'O''Fielly', 'mofiellyh@comcast.net', 'BHDOrrPyzj2');
insert into users (first_name, last_name, mail, password) values ('Jared', 'Levitt', 'jlevitti@woothemes.com', 'rWHDDCjN0xL');
insert into users (first_name, last_name, mail, password) values ('Meggi', 'Kinforth', 'mkinforthj@phpbb.com', 'AzQtnUHZ59');
insert into users (first_name, last_name, mail, password) values ('Aurel', 'Askem', 'aaskemk@cnn.com', 'vnN97FktkGi');
insert into users (first_name, last_name, mail, password) values ('Maegan', 'Tubble', 'mtubblel@cocolog-nifty.com', '52Yo6qR4');
insert into users (first_name, last_name, mail, password) values ('Claude', 'Knight', 'cknightm@ucoz.ru', 'dytxx6');
insert into users (first_name, last_name, mail, password) values ('Katey', 'Drivers', 'kdriversn@epa.gov', '0vEwMy9dd9Ig');
insert into users (first_name, last_name, mail, password) values ('Kennie', 'Mussett', 'kmussetto@yolasite.com', '8RR93rwE');
insert into users (first_name, last_name, mail, password) values ('Horton', 'Enstone', 'henstonep@icio.us', 'D5tgw8qns');
insert into users (first_name, last_name, mail, password) values ('Eleni', 'Durbyn', 'edurbynq@deliciousdays.com', 'FhdvVgcJygNf');
insert into users (first_name, last_name, mail, password) values ('Chelsea', 'Beswell', 'cbeswellr@yahoo.com', 'bPsfH604ax');
insert into users (first_name, last_name, mail, password) values ('Emmeline', 'Baber', 'ebabers@github.io', '5389iL');
insert into users (first_name, last_name, mail, password) values ('Brig', 'Cluff', 'bclufft@people.com.cn', 'dYXSl1cq');
insert into users (first_name, last_name, mail, password) values ('Goran', 'O''Shesnan', 'goshesnanu@edublogs.org', '0K5FrXZiz8Y');
insert into users (first_name, last_name, mail, password) values ('Emile', 'Leaning', 'eleaningv@blogtalkradio.com', 'MqZ3qgCC');
insert into users (first_name, last_name, mail, password) values ('Thaddeus', 'Barnham', 'tbarnhamw@issuu.com', 'DWd5G6yydkI');
insert into users (first_name, last_name, mail, password) values ('Jillian', 'Mozzi', 'jmozzix@networkadvertising.org', 'fXNLzJMBCC');
insert into users (first_name, last_name, mail, password) values ('Eleanora', 'De Cristofalo', 'edecristofaloy@google.com', 'FFciN4pIXQ');
insert into users (first_name, last_name, mail, password) values ('Lainey', 'Calveley', 'lcalveleyz@telegraph.co.uk', 'ELNOeY5DD5');
insert into users (first_name, last_name, mail, password) values ('Christa', 'Ends', 'cends10@amazon.de', 'oiYUUOGcG3');
insert into users (first_name, last_name, mail, password) values ('Mead', 'Pagen', 'mpagen11@wordpress.org', '7wpWlT0O');
insert into users (first_name, last_name, mail, password) values ('Rouvin', 'Jaggi', 'rjaggi12@privacy.gov.au', 'Clq4mlJ');
insert into users (first_name, last_name, mail, password) values ('Vachel', 'Witz', 'vwitz13@com.com', 'spw4lvnV');
insert into users (first_name, last_name, mail, password) values ('Adan', 'Fronek', 'afronek14@paypal.com', 'JyxyELQM');
insert into users (first_name, last_name, mail, password) values ('Joaquin', 'Yeabsley', 'jyeabsley15@netscape.com', 'uWK8QaOb');
insert into users (first_name, last_name, mail, password) values ('Milzie', 'Martinet', 'mmartinet16@businessweek.com', 'DXoQ34VsZLzL');
insert into users (first_name, last_name, mail, password) values ('Caesar', 'Keeler', 'ckeeler17@unesco.org', 'xDEpEa5');
insert into users (first_name, last_name, mail, password) values ('Aile', 'Kinlock', 'akinlock18@shop-pro.jp', 'S2tWP7');
insert into users (first_name, last_name, mail, password) values ('Maryellen', 'Snelling', 'msnelling19@xing.com', 'wBfeBUSqobT');
insert into users (first_name, last_name, mail, password) values ('Ricky', 'Burnsell', 'rburnsell1a@joomla.org', 'XRYlUvFcHiW');
insert into users (first_name, last_name, mail, password) values ('Patrizio', 'Kervin', 'pkervin1b@tinyurl.com', 'haAgqv6eO5yE');
insert into users (first_name, last_name, mail, password) values ('Irvin', 'Gabel', 'igabel1c@phpbb.com', 'HKsvRekzx');
insert into users (first_name, last_name, mail, password) values ('Kala', 'Bleckly', 'kbleckly1d@chron.com', 'uirvsjiV');


insert into movements (user_id, category_id, type, date, amount, concept) values (32, 3, 'receipts', '2021-10-23 10:50:36', 14.47, 'Skynoodle');
insert into movements (user_id, category_id, type, date, amount, concept) values (24, 3, 'receipts', '2020-11-19 23:49:27', 33.67, 'Livefish');
insert into movements (user_id, category_id, type, date, amount, concept) values (6, 4, 'receipts', '2021-07-13 15:18:32', 115.46, 'Devpoint');
insert into movements (user_id, category_id, type, date, amount, concept) values (13, 3, 'receipts', '2021-01-28 02:08:11', 77.36, 'Thoughtblab');
insert into movements (user_id, category_id, type, date, amount, concept) values (48, 1, 'receipts', '2020-11-28 17:08:03', 92.69, 'Roomm');
insert into movements (user_id, category_id, type, date, amount, concept) values (31, 5, 'expenses', '2021-05-06 05:55:53', 71.21, 'Yotz');
insert into movements (user_id, category_id, type, date, amount, concept) values (41, 3, 'expenses', '2021-08-31 00:04:31', 67.3, 'Kare');
insert into movements (user_id, category_id, type, date, amount, concept) values (46, 4, 'receipts', '2021-01-02 04:24:06', 105.06, 'Kwideo');
insert into movements (user_id, category_id, type, date, amount, concept) values (50, 5, 'receipts', '2021-11-05 13:32:07', 105.81, 'Yadel');
insert into movements (user_id, category_id, type, date, amount, concept) values (50, 2, 'receipts', '2021-04-20 18:23:07', 21.63, 'Aivee');
insert into movements (user_id, category_id, type, date, amount, concept) values (11, 1, 'receipts', '2021-07-03 14:16:19', 50.34, 'Browsetype');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 5, 'receipts', '2021-04-25 02:06:54', 90.59, 'Quaxo');
insert into movements (user_id, category_id, type, date, amount, concept) values (13, 4, 'expenses', '2021-03-15 15:37:51', 11.35, 'Omba');
insert into movements (user_id, category_id, type, date, amount, concept) values (42, 1, 'expenses', '2021-09-21 01:16:39', 34.91, 'Yotz');
insert into movements (user_id, category_id, type, date, amount, concept) values (39, 2, 'expenses', '2021-05-30 15:13:12', 34.67, 'Kwilith');
insert into movements (user_id, category_id, type, date, amount, concept) values (37, 4, 'receipts', '2021-01-02 13:20:23', 60.94, 'Centidel');
insert into movements (user_id, category_id, type, date, amount, concept) values (47, 1, 'receipts', '2021-03-01 22:42:53', 12.39, 'Meejo');
insert into movements (user_id, category_id, type, date, amount, concept) values (7, 4, 'receipts', '2021-06-03 14:27:19', 119.15, 'Quaxo');
insert into movements (user_id, category_id, type, date, amount, concept) values (48, 5, 'receipts', '2021-03-28 05:00:48', 48.2, 'Topicstorm');
insert into movements (user_id, category_id, type, date, amount, concept) values (33, 5, 'receipts', '2021-03-10 22:49:26', 43.91, 'Bluezoom');
insert into movements (user_id, category_id, type, date, amount, concept) values (47, 1, 'expenses', '2021-11-03 15:50:05', 90.03, 'Fivespan');
insert into movements (user_id, category_id, type, date, amount, concept) values (7, 3, 'receipts', '2021-07-28 16:19:25', 77.05, 'Dynazzy');
insert into movements (user_id, category_id, type, date, amount, concept) values (29, 3, 'receipts', '2021-02-08 19:49:23', 41.32, 'Livetube');
insert into movements (user_id, category_id, type, date, amount, concept) values (34, 1, 'receipts', '2021-05-25 20:01:40', 82.11, 'Jatri');
insert into movements (user_id, category_id, type, date, amount, concept) values (35, 3, 'receipts', '2021-08-17 13:25:12', 41.88, 'Meedoo');
insert into movements (user_id, category_id, type, date, amount, concept) values (44, 3, 'expenses', '2021-07-03 10:39:03', 76.75, 'Voonte');
insert into movements (user_id, category_id, type, date, amount, concept) values (3, 3, 'expenses', '2021-01-31 04:28:58', 35.43, 'Dabjam');
insert into movements (user_id, category_id, type, date, amount, concept) values (36, 1, 'receipts', '2021-07-19 23:10:02', 85.58, 'Bubbletube');
insert into movements (user_id, category_id, type, date, amount, concept) values (3, 2, 'expenses', '2021-03-30 16:14:08', 87.52, 'Agivu');
insert into movements (user_id, category_id, type, date, amount, concept) values (27, 4, 'receipts', '2020-12-23 09:22:25', 55.03, 'Npath');
insert into movements (user_id, category_id, type, date, amount, concept) values (13, 5, 'expenses', '2021-03-26 06:30:54', 72.39, 'Quamba');
insert into movements (user_id, category_id, type, date, amount, concept) values (11, 4, 'receipts', '2021-11-15 21:15:37', 26.22, 'InnoZ');
insert into movements (user_id, category_id, type, date, amount, concept) values (40, 3, 'receipts', '2021-04-19 04:12:41', 57.27, 'Tambee');
insert into movements (user_id, category_id, type, date, amount, concept) values (10, 4, 'receipts', '2021-01-23 19:51:14', 88.67, 'JumpXS');
insert into movements (user_id, category_id, type, date, amount, concept) values (28, 3, 'expenses', '2021-10-15 01:14:07', 117.77, 'Camimbo');
insert into movements (user_id, category_id, type, date, amount, concept) values (48, 2, 'expenses', '2021-01-04 12:00:43', 35.67, 'Izio');
insert into movements (user_id, category_id, type, date, amount, concept) values (38, 4, 'expenses', '2021-03-23 18:51:52', 76.57, 'Meetz');
insert into movements (user_id, category_id, type, date, amount, concept) values (11, 1, 'expenses', '2021-01-03 21:06:10', 43.77, 'Brainverse');
insert into movements (user_id, category_id, type, date, amount, concept) values (4, 3, 'expenses', '2021-05-24 06:44:57', 91.94, 'Aivee');
insert into movements (user_id, category_id, type, date, amount, concept) values (43, 3, 'receipts', '2021-01-19 23:28:32', 108.25, 'Shufflester');
insert into movements (user_id, category_id, type, date, amount, concept) values (47, 3, 'expenses', '2021-02-08 05:16:10', 55.45, 'Shufflester');
insert into movements (user_id, category_id, type, date, amount, concept) values (3, 1, 'expenses', '2021-10-03 10:51:31', 118.95, 'Mydo');
insert into movements (user_id, category_id, type, date, amount, concept) values (6, 3, 'expenses', '2021-07-02 15:42:37', 39.94, 'Oodoo');
insert into movements (user_id, category_id, type, date, amount, concept) values (8, 3, 'receipts', '2021-05-03 18:38:45', 103.66, 'Flipopia');
insert into movements (user_id, category_id, type, date, amount, concept) values (49, 3, 'receipts', '2021-04-08 03:32:32', 63.45, 'Photofeed');
insert into movements (user_id, category_id, type, date, amount, concept) values (18, 4, 'receipts', '2021-07-02 01:46:59', 79.55, 'Fatz');
insert into movements (user_id, category_id, type, date, amount, concept) values (12, 4, 'receipts', '2021-04-11 13:06:52', 51.66, 'Meemm');
insert into movements (user_id, category_id, type, date, amount, concept) values (7, 4, 'expenses', '2021-07-06 03:10:33', 42.46, 'Avamba');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 5, 'expenses', '2021-02-08 16:16:03', 91.08, 'Thoughtstorm');
insert into movements (user_id, category_id, type, date, amount, concept) values (46, 1, 'receipts', '2021-08-03 13:59:00', 37.18, 'Eire');

insert into movements (user_id, category_id, type, date, amount, concept) values (1, 3, 'receipts', '2021-10-23 10:50:36', 14.47, 'Skynoodle');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 3, 'receipts', '2020-11-19 23:49:27', 33.67, 'Livefish');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 4, 'receipts', '2021-07-13 15:18:32', 115.46, 'Devpoint');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 3, 'receipts', '2021-01-28 02:08:11', 77.36, 'Thoughtblab');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 1, 'receipts', '2020-11-28 17:08:03', 92.69, 'Roomm');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 5, 'expenses', '2021-05-06 05:55:53', 71.21, 'Yotz');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 3, 'expenses', '2021-08-31 00:04:31', 67.3, 'Kare');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 4, 'receipts', '2021-01-02 04:24:06', 105.06, 'Kwideo');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 5, 'receipts', '2021-11-05 13:32:07', 105.81, 'Yadel');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 2, 'receipts', '2021-04-20 18:23:07', 21.63, 'Aivee');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 1, 'receipts', '2021-07-03 14:16:19', 50.34, 'Browsetype');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 5, 'receipts', '2021-04-25 02:06:54', 90.59, 'Quaxo');
insert into movements (user_id, category_id, type, date, amount, concept) values (1, 4, 'expenses', '2021-03-15 15:37:51', 11.35, 'Omba');


INSERT INTO `personal_finances`.`categories` (`name`, `image`) VALUES ('others', 'icon-dollar.png');
INSERT INTO `personal_finances`.`categories` (`name`, `image`) VALUES ('hotel', 'icon-hotel.png');
INSERT INTO `personal_finances`.`categories` (`name`, `image`) VALUES ('airplane', 'icon-airplane.png');
INSERT INTO `personal_finances`.`categories` (`name`, `image`) VALUES ('bus', 'icon-bus.png');
INSERT INTO `personal_finances`.`categories` (`name`, `image`) VALUES ('supermarket', 'icon-supermarket.png');
INSERT INTO `personal_finances`.`categories` (`name`, `image`) VALUES ('food', 'icon-food.png');
INSERT INTO `personal_finances`.`categories` (`name`, `image`) VALUES ('toll', 'icon-toll.png');
INSERT INTO `personal_finances`.`categories` (`name`, `image`) VALUES ('party', 'icon-party.png');
